import { Card, CardHeader, CardDescription, CardTitle, CardContent } from "@/components/ui/card";
import { useEffect, useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import GradesTable from "@/components/grades-table";
import type { Grade } from "@/components/grades-table";

const Home: NextPage = () => {

  const [grades, setGrades] = useState<Grade[]>([{
    testGrade: '63',
    testWeight: '0.25',
    testName: 'Test 1'
  }]);
  const [gradeGoal, setGradeGoal] = useState('')
  const [requiredGrade, setRequiredGrade] = useState<number | null>(null)

  useEffect(() => {
    handleGradeChange(grades, gradeGoal);
  }, [grades, gradeGoal])

  function handleGradeChange(grades: Grade[], gradeGoal: string) {

    if (!gradeGoal || grades.length < 1) {
      setRequiredGrade(null); return;
    }

    const goal = parseFloat(gradeGoal);

    let weightTotal = 0;
    let completedTotal = 0;

    for (const { testGrade, testWeight } of grades) {
      const weight = parseFloat(testWeight)
      const grade = parseFloat(testGrade);
      weightTotal += weight;
      completedTotal += (grade * weight);
    }

    const required = (goal - completedTotal) / (1 - weightTotal);
    setRequiredGrade(required);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen pt-12 pb-6 w-screen flex-col items-center justify-center">
        <div className="w-full h-full flex flex-col justify-center items-center">
          <div className="flex xl:w-full h-full">
            <Card className="mx-12 w-full h-full pt-2">
              <CardHeader>
                <CardTitle className="text-3xl flex flex-col items-start pb-3 font-bold leading-tight tracking-tighter md:text-4xl xl:text-5xl lg:leading-[1.1]">
                  <span className="text-2xl pb-3 font-bold pr-4 rounded-xl  p-3 mb-4">1.</span>
                  <span>Add your tests/assignments</span>
                </CardTitle>
                <CardDescription className="text-lg text-muted-foreground sm:text-xl">
                  Add the grades that you already know, so you can work out what you need!
                </CardDescription>
              </CardHeader>
              <CardContent>
                {<GradesTable onChange={(gs) => setGrades(gs)} />}
              </CardContent>
            </Card>
            <Card className="mx-12 w-full pt-2 h-full">
              <CardHeader>
                <CardTitle className="text-3xl flex flex-col items-start pb-3 font-bold leading-tight tracking-tighter md:text-4xl xl:text-5xl lg:leading-[1.1]">
                  <span className="text-2xl pb-3 font-bold pr-4 rounded-xl  p-3 mb-4">2.</span>
                  <span className="text-primary">Check what you need</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div>
                  <label
                    htmlFor="email"
                    className="block text-xs text-gray-600 uppercase"
                  >
                    Enter your desired grade (%)
                  </label>
                  <input
                    value={gradeGoal}
                    onChange={(e) => setGradeGoal(e.target.value)}
                    id="grade"
                    name="grade"
                    type="grade"
                    placeholder="e.g., 67"
                    autoComplete="grade"
                    required
                    className="mt-1 block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-black focus:outline-none focus:ring-black sm:text-sm"
                  />
                </div>
                <div className="h-full">
                  {requiredGrade ? (<>
                    <p>
                      You need {requiredGrade.toFixed(1)}% to achieve your goal.
                    </p>
                  </>) : (<>
                  </>)}
                </div>
              </CardContent>
            </Card>
          </div >
        </div>
      </main>
    </>
  );
};

export default Home;
